"""empty message

Revision ID: 70947667e6b3
Revises: 6249fce1ead9
Create Date: 2023-07-07 21:06:15.691094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70947667e6b3'
down_revision = '6249fce1ead9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monoisotopic_mass', sa.Float(), nullable=False))
        batch_op.drop_column('adduct')
        batch_op.drop_column('standard_class')
        batch_op.drop_column('mass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('standard_class', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('adduct', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('monoisotopic_mass')

    # ### end Alembic commands ###
